[project]
name = "neohcm"
version = "0.1.5"
description = "Neo HCM for Frappe"
readme = "README.md"
requires-python = ">=3.10,<3.12"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.bench.frappe-dependencies]
frappe = ">=15.0.0,<16.0.0"
